# Generated by Django 4.2.13 on 2026-04-29 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import processing.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # =====================================================
        # VideoSync Model
        # =====================================================
        migrations.CreateModel(
            name='VideoSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=processing.models.video_upload_path)),
                ('script', models.TextField()),
                ('hand_gestures', models.BooleanField(default=True)),
                ('head_movement', models.BooleanField(default=True)),
                ('facial_expressions', models.BooleanField(default=True)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('processing', 'Processing'),
                        ('completed', 'Completed'),
                        ('failed', 'Failed')
                    ],
                    default='pending',
                    max_length=20
                )),
                ('result_video', models.FileField(blank=True, null=True, upload_to=processing.models.result_upload_path)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='video_syncs',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),

        # =====================================================
        # LipsyncJob Model
        # =====================================================
        migrations.CreateModel(
            name='LipsyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('avatar_id', models.CharField(db_index=True, max_length=255)),
                ('audio_id', models.CharField(max_length=255)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('processing', 'Processing'),
                        ('completed', 'Completed'),
                        ('failed', 'Failed')
                    ],
                    default='pending',
                    max_length=20
                )),
                ('error_message', models.TextField(blank=True, null=True)),
                ('video_path', models.CharField(blank=True, max_length=512)),
                ('video_url', models.URLField(blank=True, max_length=512)),
                ('num_frames', models.IntegerField(default=0)),
                ('duration_sec', models.FloatField(default=0.0)),
                ('elapsed_sec', models.FloatField(default=0.0)),
                ('stage_timings', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='lipsync_jobs',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'status'], name='processing_user_status_idx'),
                    models.Index(fields=['avatar_id'], name='processing_avatar_idx'),
                ],
            },
        ),
    ]