# Generated by Django 4.2.13 on 2026-05-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lipsyncjob',
            new_name='processing__user_id_d01ba9_idx',
            old_name='processing_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='lipsyncjob',
            new_name='processing__avatar__f8c011_idx',
            old_name='processing_avatar_idx',
        ),
        migrations.AlterField(
            model_name='lipsyncjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
