# Generated by Django 4.2.13 on 2026-05-05 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_projects', models.IntegerField(default=0)),
                ('videos_created', models.IntegerField(default=0)),
                ('avatars_count', models.IntegerField(default=0)),
                ('translations_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('text_to_video', 'Text to Video'), ('record_sync', 'Record & Sync'), ('avatar', 'Avatar'), ('voice_clone', 'Voice Clone'), ('translation', 'Translation')], max_length=50)),
                ('avatar_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('voice_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_language', models.CharField(blank=True, max_length=50, null=True)),
                ('target_language', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
