# Generated by Django 4.2.13 on 2026-04-28 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_name', models.CharField(max_length=100)),
                ('avatar_type', models.CharField(choices=[('ai', 'AI Avatar'), ('image', 'Image Upload'), ('video', 'Video Upload')], default='ai', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('age_range', models.CharField(blank=True, choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56-70', '56-70')], max_length=20, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('diverse', 'Diverse'), ('asian', 'Asian'), ('caucasian', 'Caucasian'), ('african', 'African'), ('hispanic', 'Hispanic'), ('middle_eastern', 'Middle Eastern')], max_length=50, null=True)),
                ('hair_style', models.CharField(blank=True, choices=[('long', 'Long'), ('short', 'Short'), ('curly', 'Curly'), ('bald', 'Bald')], max_length=50, null=True)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_avatars/')),
                ('user_video', models.FileField(blank=True, null=True, upload_to='user_videos/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
