# Generated by Django 6.0.4 on 2026-04-17 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(blank=True, max_length=10)),
                ('target_language_name', models.CharField(blank=True, max_length=50)),
                ('original_text', models.TextField()),
                ('corrected_text', models.TextField(blank=True, null=True)),
                ('sanitized_text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/')),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=10)),
                ('tld', models.CharField(default='com', max_length=5)),
                ('slow', models.BooleanField(default=False)),
                ('voice_type', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10)),
                ('engine', models.CharField(blank=True, choices=[('google_cloud_tts', 'Google Cloud TTS'), ('gtts_fallback', 'gTTS Fallback'), ('xtts_cloned', 'XTTS Cloned Voice'), ('', 'Unknown')], default='', max_length=30)),
                ('voice_sample_file', models.FileField(blank=True, help_text='Uploaded voice sample used for cloning', null=True, upload_to='voice_samples/%Y/%m/%d/')),
                ('cloned_voice_id', models.CharField(blank=True, help_text='UUID referencing the stored speaker embedding', max_length=100, null=True)),
                ('is_cloned', models.BooleanField(default=False, help_text='True when audio was generated using a cloned voice')),
                ('character_count', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClonedVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional user-supplied label', max_length=100)),
                ('sample_file', models.FileField(upload_to='voice_samples/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloned_voices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
