# Generated by Django 6.0.4 on 2026-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='target_language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
