# Generated by Django 4.2.13 on 2026-04-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generation', '0002_alter_audiofile_target_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='target_language',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
